### ISSUE TITLE
Redmine 2.0.x compatibility

### ISSUE THREAD

**Issue by jwalkerbg** [cforce/projects_tree_view#5]
This plugin does not work in redmine 2.0.x because of dispatcher that does not exist in rails 3.2.3 and prevents Redmine to start.

I made a patch from http://www.redmine.org/boards/3/topics/30930?r=30973#message-30973 and Redmine started successfully. OK, but it seems that the plugin does nothing - tree view of the projects does not appear. They are listed as there were no treeview plugin.

**Comment by cforce** [comment]
Please checkout for and report errors here.

https://github.com/cforce/projects_tree_view/pull/6

**Comment by plikus** [comment]
Please, give me some advice what I did in correct?

 I tried this branch 2.0x, but it doesn't work. (2.0.3 Redmine)
At first, there was an error over dispetcher. I followed advice from  http://www.redmine.org/boards/3/topics/30930?r=30973#message-30973... error doesn't happened, but tree view didnt appear as well. 

So I absolutelly the same to jwalkerbg.

Thank you!

**Comment by cforce** [comment]
https://github.com/cforce/projects_tree_view/tree/redmine2.x
