### ISSUE TITLE
Redmine 2, Ruby 3 and .html_safe

### ISSUE THREAD

**Issue by stonier** [cforce/projects_tree_view#7]
It's missing quite a few html_safe arguments in both the project view and admin project view (especially this one). I've been using the redmine2.x branch with redmine 2.0.1.

Easy to identify them by viewing the page source (in chrome) and looking for anything like 

```
&lt;span style=&quot;padding-left: 0em;&quot;&gt;
```

instead of the properly substituted <span style="padding-left: 0em;">.

This effects output in 
- app/views/admin/projects.html.erb
- app/views/index.html.erb

**Comment by danmunn** [comment]
Fixed in pull request 9

**Comment by cforce** [comment]
https://github.com/cforce/projects_tree_view/tree/redmine2.x
